AWS_REGION: us-east-2
AWS_NODE_AZ: us-east-21
AWS_PUBLIC_NODE_CIDR: 10.0.0.0/28
AWS_PRIVATE_NODE_CIDR: 10.0.0.16/28
AWS_PUBLIC_SUBNET_ID: subnet-063943938fa17a82c
AWS_PRIVATE_SUBNET_ID: subnet-0a59f6b95f069555f
AWS_LB_SCHEME: Internal
AWS_SSH_KEY_NAME: tkg-tkg-aws-default
AWS_VPC_CIDR: 10.0.0.0/20
AWS_VPC_ID: vpc-09e28d40340d708a4
CLUSTER_CIDR: 100.96.0.0/11
BASTION_HOST_ENABLED: "true"
CONTROL_PLANE_MACHINE_TYPE: t3.medium
NODE_MACHINE_TYPE: t3.large