AWS_REGION: us-east-2
AWS_NODE_AZ: us-east-2a
AWS_PUBLIC_NODE_CIDR: 10.0.0.96/28
AWS_PRIVATE_NODE_CIDR: 10.0.1.0/24
AWS_PUBLIC_SUBNET_ID: subnet-0b62ab07234682be5
AWS_PRIVATE_SUBNET_ID: subnet-075acced6e27d6e57
AWS_SSH_KEY_NAME: tkg-tkg-aws-default
AWS_VPC_CIDR: 10.0.0.0/20
AWS_VPC_ID: vpc-0b7ec8c65fb086e7f
CLUSTER_CIDR: 100.96.0.0/11
BASTION_HOST_ENABLED: "true"
CONTROL_PLANE_MACHINE_TYPE: t3.medium
NODE_MACHINE_TYPE: t3.large
overridesFolder: /Users/azwickey/.tkg/overrides
cert-manager-timeout: 30m0s
NODE_STARTUP_TIMEOUT: 20m